sonar.projectKey=SistemaReservasHotel
sonar.projectName=SistemaReservasHotel
sonar.projectVersion=1.0

sonar.sources=src
sonar.language=java

sonar.java.binaries=build/web/WEB-INF/classes

sonar.sourceEncoding=UTF-8
